# Generated by Django 4.2.7 on 2023-11-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('plot', models.TextField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
